###
POST http://127.0.0.1:3000/api/wilder/create HTTP/1.1
content-type: application/json

{
    "name": "Thomas",
    "city": "Londres",
    "skills":[
        {"title": "express", "votes":5},
        {"title": "mongo", "votes":12}
    ]
}

###
GET http://127.0.0.1:3000/api/wilder/read HTTP/1.1

###

DELETE http://127.0.0.1:3000/api/wilder/delete/622783bba94be564d464bcad HTTP/1.1


###
PUT http://127.0.0.1:3000/api/wilder/update/622778ceeb5c77c442ec4dfe HTTP/1.1
content-type: application/json

{
    "name": "Thomas",
    "city": "SF",
    "skills": [
        {"title": "express", "votes":5},
        {"title": "mongo", "votes":12}
    ]
}